plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.10' apply false
	id 'io.spring.dependency-management' version '1.1.7' apply false
}

allprojects {
    group = 'com.teno'
    version = '0.0.1-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'java-library'
    apply plugin: 'java-test-fixtures'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'
    apply plugin: 'checkstyle'
    apply plugin: 'jacoco'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    dependencies {
        compileOnly 'org.projectlombok:lombok'
        annotationProcessor 'org.projectlombok:lombok'

        implementation 'com.github.therapi:therapi-runtime-javadoc:0.15.0'
        annotationProcessor 'com.github.therapi:therapi-runtime-javadoc-scribe:0.15.0'

        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

        testImplementation sourceSets.main.output
    }

    test {
        useJUnitPlatform()
        finalizedBy jacocoTestReport
    }

    checkstyle {
        toolVersion = '10.12.5'
        configFile = rootProject.file("config/checkstyle/checkstyle.xml")
        ignoreFailures = false // 규칙 위반 시 빌드를 실패시킴 (에러 발생)
    }

    jacocoTestReport {
        dependsOn test
        reports {
            xml.required = true // CI 연동용
            html.required = true // 개발자 확인용
        }
    }

    jacocoTestCoverageVerification {
        violationRules {
            rule {
                enabled = true
                element = 'CLASS'
                // 커버리지 체크 제외 대상
                excludes = [
                    '**.*Application*',
                    '**.*Config*',
                    '**.*Dto*',
                    '**.*Request*',
                    '**.*Response*',
                    '**.*Exception*',
                    '**/Q*'
                ]

                // 커버리지 기준 설정
                limit {
                    counter = 'LINE' // 라인 커버리지 기준
                    value = 'COVEREDRATIO'
                    minimum = 0.30
                }
            }
        }
    }
}

configure(subprojects.findAll { it.name in ['deal', 'order', 'store', 'system'] }) {
    bootJar.enabled = false
    jar.enabled = true

    dependencies {
        implementation project(':common')

        implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    }
}