rootProject.name = 'openmarket'

// 실행 모듈:
// 독립된 도메인 모듈들을 결합하여 특정 비즈니스 목적의 서비스를 완성하는
// '런타임 정책 정의 및 인프라 통합' 계층
include 'api-server'

// 공통 모듈:
// 프로젝트 전역의 데이터 무결성과 통신 정합성을 보장하기 위한
// '도메인 불가지론적 표준 규약 및 공용 라이브러리' 계층
include 'common'

// 비즈니스 도메인 모듈
include 'user'
include 'deal'
include 'order'
include 'store'
include 'system'