bootJar { enabled = true }
jar { enabled = false }

dependencies {
    implementation project(':common')
    implementation project(':user')
    implementation project(':deal')
    implementation project(':order')
    implementation project(':store')
    implementation project(':system')

    implementation 'org.springframework.boot:spring-boot-starter-web'

    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-mysql'

    runtimeOnly 'com.mysql:mysql-connector-j'

    testImplementation 'com.tngtech.archunit:archunit-junit5:1.3.0'
    testImplementation 'jakarta.persistence:jakarta.persistence-api'

    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-security'
}