bootJar { enabled = false }
jar { enabled = true }

dependencies {
    implementation project(':common')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-security'

    testImplementation(testFixtures(project(":common")))

    implementation platform('software.amazon.awssdk:bom:2.41.31')
    implementation 'software.amazon.awssdk:s3'
}